### ISSUE TITLE
Create a page to list of suggest builders

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#111]
It would be nice to have a place to reference what builders are "suggested". For example, in documentation or various implementations where the configuration of builders is necessary we can point the user to a list of builders to use.

One example is the tekton task: https://github.com/tektoncd/catalog/tree/master/buildpacks

Notes:
- Consider having a central catalog of suggested builders and stacks that both the docs and pack read from.

**Comment by dfreilich** [comment]
buildpacks/pack#666 should be helpful for this. Blocking on that.

**Comment by jromero** [comment]
I think we should get this done independent of buildpacks/pack#666 provided that that issue would require some further discussion.

**Comment by jromero** [comment]
It would be _really_ nice if builders and stacks were listed on the registry. see https://github.com/buildpacks/registry-api/issues/56

**Comment by jromero** [comment]
Let's block this on the expectation that the registry will have this information ^.
