### ISSUE TITLE
Can we rebuild the docs when a new version of pack is released?

### ISSUE THREAD

**Issue by zmackie** [buildpacks/docs#115]
I ran into #113 which, at the root of it, seems related to the fact that we're not currently "rebuilding" our docs when a new version of `pack` is released. In general our docs should, if possible, reflect the current command set, etc. so it would be neat if we could find a way to accomplish this.

Github actions?

**Comment by dfreilich** [comment]
This is important, as we'll have to keep this in mind when we cut `v11` in `pack`. We still have a version baked into the linux download here: https://github.com/buildpacks/docs/blob/master/content/docs/install-pack.md#linux

I hope to add some tooling around rebuilding the docs as part of #119 , but there should perhaps be some more about doing a version.
