### ISSUE TITLE
Document launch process

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#125]
As an app developer, I would like to know all the ways in which I can interact with an image created with Cloud Native Buildpacks.

Some use cases:
- Pass arguments to a `direct` process type
- Execute arbitrary commands
- Selecting process type

Relates to https://github.com/buildpacks/lifecycle/issues/280

**Comment by dfreilich** [comment]
Blocked on https://github.com/buildpacks/rfcs/pull/84

**Comment by jromero** [comment]
Blocked by https://github.com/buildpacks/spec/issues/105

**Comment by yaelharel** [comment]
The "blocked" label should be removed since https://github.com/buildpacks/rfcs/pull/84 was merged and https://github.com/buildpacks/spec/issues/105 was closed.
