### ISSUE TITLE
Technical overview documentation

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpacks/docs#127]
It would be helpful for the broader community to have access to some of the decks from conference presentations, etc, in addition to the videos that are already accessible. For now, a PDF would be great, but eventually some could make their way into becoming actual web pages.

**Comment by dfreilich** [comment]
Good to add:
- CNCF Buildpacks Presentation - [slides](https://docs.google.com/presentation/d/1InW4LbgFb8dSCCgbN7hozNTAFZTsIVBWxm8sv87TjZs/edit#slide=id.g40918ba3a5_1_0)

A list of videos at conferences about Buildpacks. For instance:
- [Intro: Cloud Native Buildpacks - Terence Lee, Heroku & Stephen Levine, Pivotal](https://www.youtube.com/watch?v=WTE8iu_vnbk&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D)
- [Bringing Cloud Native Buildpacks to Kubernetes - Dr Nic Williams, Stark & Wayne](https://www.youtube.com/watch?v=kt2kxxypGCI&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D)
- [Intro to Cloud Native Buildpacks - Terence Lee, Heroku & Emily Casey, Pivotal](https://www.youtube.com/watch?v=SK6e_ZatOaw&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D)
- [Deep Dive: Cloud Native Buildpacks - Joe Kutner, Heroku & Stephen Levine, Pivotal](https://www.youtube.com/watch?v=j9Ak5YLrihU&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D)

**Comment by dfreilich** [comment]
Some additional presentations:
* @dfreilich / @natalieparellano Kubecon NA 2020 Talk - [video](https://youtu.be/RNN8XwRWGjk), [slides](https://docs.google.com/presentation/d/1vDv33oHU277mh6oCP7vBqQomMpPFIuzSmMTtfaQyBoY/edit?usp=sharing)
* @hone talk on CNBs – [slides](https://docs.google.com/presentation/d/1G6slFtpHPjIx-JHzRXAjJcWnQx6a5mRgW6QO_3XqeQo/edit?usp=sharing)
* @jromero talk on CNBS – [slides](https://docs.google.com/presentation/d/1ERcLuC2f2xAcD8d49BmtJ6e6bapIVpgmhe94wW7Upl0/edit?usp=sharing)

**Comment by danielleadams** [comment]
[slides](https://slides.com/danielleadams/cnbs-node-js-interactive-19) from Node.js Interactive Conf 2019.
