### ISSUE TITLE
cloudfoundry/cnb:cflinuxfs3 builder has silent dependency on gcloud

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#129]
**On Page:** [Building blocks of a Cloud Native Buildpack](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb/)

When attempting to use the `cloudfoundry/cnb:cflinuxfs3` builder for the test ruby app, it failed out because `ERROR: invalid run-image 'gcr.io/paketo-buildpacks/run:full-cnb-cf': error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: `` `

It seems that `cloudfoundry/cnb:cflinuxfs3` has a silent dependency on `gcloud` being in the path. Should that be explicitly noted? 

The full logs are: 
```
$  pack build ruby-app -p ruby-sample-app/ --buildpack temp-ruby-cnb/
cflinuxfs3: Pulling from cloudfoundry/cnb
7f9bce95fa3f: Pull complete
...
89732bc75041: Pull complete
Digest: sha256:13202cf555bfc209c7cd2f35fb35e5557b1410ab99623e656fa74a23f560755a
Status: Downloaded newer image for cloudfoundry/cnb:cflinuxfs3
ERROR: invalid run-image 'gcr.io/paketo-buildpacks/run:full-cnb-cf': error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ``
```

**Comment by jromero** [comment]
This seems like a change/issue with the transition to Paketo. /cc: @kvedurmu

We should probably change our tutorial to use our sample builders to prevent these sort of issues in the future.

**Comment by jromero** [comment]
@dfreilich do you have credentials for gcr.io configured in your `$HOME/.docker/config.json`?

**Comment by dfreilich** [comment]
That's why I wanted to call it out. Using sample builders, like with the Apps Journey, should help safeguard it. 

I solved that issue, `gcloud` just wasn't on my PATH since I reconfigured my workstation

**Comment by dfreilich** [comment]
The issue was, as @jromero and @ekcasey said, because I had `gcloud` configured in my `$HOME/.docker/config.json`, but I didn't have it on my `PATH`.
