### ISSUE TITLE
Example in "An App’s Brief Journey" doesn't work

### ISSUE THREAD

**Issue by arthurk** [buildpacks/docs#132]
Hi I just installed pack and tried to follow the "An App’s Brief Journey from Source to Image" example but it fails:

```
$ pwd
/Users/asd/Code/samples/apps/java-maven

$ pack build myapp --builder cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-builder
Digest: sha256:85cb879dfcbcbd97425f3b8b92278f5049d721f31a026695e6f442b31c9a4fb7
Status: Image is up to date for cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-stack-run
Digest: sha256:41609c85c96a36136d6af84294177f0390fadcae2200671d9d705a8cb61f21a3
Status: Image is up to date for cnbs/sample-stack-run:bionic
===> DETECTING
[detector] io.buildpacks.samples.java-maven 0.0.1
===> ANALYZING
[analyzer] Warning: Image "index.docker.io/library/myapp:latest" not found
===> RESTORING
===> BUILDING
[builder] ---> Java buildpack
[builder] ---> Installing JDK
[builder] 
[builder] gzip: stdin: unexpected end of file
[builder] tar: Child returned status 1
[builder] tar: Error is not recoverable: exiting now
[builder] ERROR: failed to build: exit status 2
ERROR: failed with status code: 7
```

```
$ pack --version
0.10.0+git-06d9983.build-259
$ docker --version
Docker version 19.03.8, build afacb8b
```

What am I doing wrong? (The bash example in the app directory works fine)

**Comment by jromero** [comment]
Not  having any issues running these examples locally. Based on the error it appears like potentially an intermittent network issue or some network restrictions as it tries to download the JDK.

[Here](https://asciinema.org/a/ERd3pRctGa0NhCRZL4griyNo2) is a temp screen capture of the successfully executed commands.

Are you able to successfully `curl` [these](https://github.com/buildpacks/samples/blob/master/buildpacks/java-maven/bin/build#L19-L28) endpoints?

**Comment by arthurk** [comment]
Yep you're right, there must've been some network issue. I've ran the example again and it works fine. Thanks!

**Comment by cbommb** [comment]
https://apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz is not available anymore.

Only active versions 3.8.x and 3.9.X are currently published at https://downloads.apache.org/maven/maven-3/

3.5.4 should be retrieved from archives : https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/

**Comment by AidanDelaney** [comment]
Thanks for the heads'up on this.  https://github.com/buildpacks/samples/pull/184 should hopefully address it.
