### ISSUE TITLE
ERROR: processing order: no versions of buildpack io.buildpacks.samples.hello-world were found on the builder

### ISSUE THREAD

**Issue by cmoulliard** [buildpacks/docs#134]
**On Page:** [Create a builder](https://buildpacks.io/docs/operator-guide/create-a-builder/)

I executed the command as suggested `pack create-builder my-builder:bionic --builder-config ./builder.toml` and pack is reporting the following error

```
bionic: Pulling from cnbs/sample-stack-build
Digest: sha256:bf945248e8add4ad2bd375463bdbc16d2214afa39dd397bb3359acc60119ffce
Status: Image is up to date for cnbs/sample-stack-build:bionic
hello-universe: Pulling from cnbs/sample-package
f88cb176274b: Pull complete
0c93e87ede7b: Pull complete
683a16f12fa8: Pull complete
Digest: sha256:a3dc49636f0dabd481906d1ee52c96e7daace1dea8b029c9ac36c27abe4cb1f6
Status: Downloaded newer image for cnbs/sample-package:hello-universe
ERROR: processing order: no versions of buildpack io.buildpacks.samples.hello-world were found on the builder
```

**Comment by jromero** [comment]
Thank you for bringing this to our attention. We'll try to update the docs as soon as possible. We are in the process of changing the sample buildpacks to be registry compliant (https://github.com/buildpacks/samples/pull/70, https://github.com/buildpacks/samples/pull/71)
