### ISSUE TITLE
Document Buildpack Plan

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#137]
Based on #67 

We should better explain and document the format of the buildpack plan. What it looks like in practice, and how it should be used by buildpack authors. 

References: https://github.com/buildpack/spec/blob/master/buildpack.md#buildpack-plan-toml

This should entail:

* Explaining it as part of the tutorial
* Adding it to the buildpack API reference

**Comment by samj1912** [comment]
Seems to be added here - https://buildpacks.io/docs/reference/spec/buildpack-api/#build-plan

**Comment by samj1912** [comment]
There could be some improvements, but overall the issue is done as the BP author's guide also uses this example.
