### ISSUE TITLE
Buildpack Groups

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#147]
## Summary

As an app developer troubleshooting why my app is failing to build, I'd like to know how buildpacks work together in "groups".

## What questions should this documentation answer?
- What are buildpack groups?
- How do buildpacks detection works within the context of a group?
- What does it mean for a buildpack to be optional in a group?

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information

- Should be listed in [Components](https://buildpacks.io/docs/concepts/components/).
- Here's where the term comes from: https://buildpacks.io/docs/reference/builder-config/#order-_list-required_

**Comment by samj1912** [comment]
cc: @buildpacks/buildpack-authors-tooling-contributors in case there is anything to add.
