### ISSUE TITLE
Add documentation of configuration files

### ISSUE THREAD

**Issue by danielleadams** [buildpacks/docs#148]
## Summary
Similar to https://github.com/buildpacks/docs/issues/137, it would be useful to have explanations of the different configuration files that are either included in buildpacks or created during the lifecycle.

## What questions should this documentation answer?
- What is a build plan?
- How is a build plan different from a buildpack plan?
- What is a bill of materials? How is it different from the buildpack plan?
- What is the `store.toml` used for?

## Who is the target audience for this documentation?

- [ ] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information
Not really, but it would be helpful to have descriptions of everything here: https://github.com/buildpacks/spec/blob/master/buildpack.md#data-format.

**Comment by hone** [comment]
@danielleadams by this do you also mean the internal lifecycle files?

**Comment by danielleadams** [comment]
This would just be for files that are created by the buildpack authors and files that may be created by buildpack code that buildpack authors write.

**Comment by jromero** [comment]
Wonder if this could be broken down into smaller chunks. By the looks of it this could be an epic.

**Comment by danielleadams** [comment]
I agree - happy to open smaller issues (or work on smaller pull requests that link back to this).

**Comment by dfreilich** [comment]
@danielleadams The Build Plan is documented here, though I'm all for adding to it: https://buildpacks.io/docs/reference/buildpack-api/#build-plan

**Comment by danielleadams** [comment]
@dfreilich I see it now... maybe we could add a ToC at the top of that page then. It gets a little lost with all the other text on that page

**Comment by dfreilich** [comment]
Agreed. Or maybe we should move it to another reference page entirely?

**Comment by dfreilich** [comment]
Should this also include `project.toml`'s? It doesn't seem to be documented anywhere.

**Comment by danielleadams** [comment]
I think so... maybe in a different issue? Since that will apply to App Developer and not Buildpack Authors.

**Comment by natalieparellano** [comment]
I'll go ahead and open an issue to document the BOM. Probably it makes sense to do this when https://github.com/buildpacks/lifecycle/issues/396 has been completed.

**Comment by natalieparellano** [comment]
Another file to document: report.toml

**Comment by natalieparellano** [comment]
Here are some thoughts:

Under "buildpack author's guide", we could include documentation or links to the following:
* launch.toml
* build.toml
* store.toml
* build plan (described here: https://buildpacks.io/docs/reference/spec/buildpack-api/#build-plan )
* buildpack plan
* layer content metadata (described here: https://buildpacks.io/docs/reference/spec/buildpack-api/#layers )
* buildpack.toml (described here: https://buildpacks.io/docs/reference/spec/buildpack-api/#buildpacktoml )
* exec.d output

In general, do we like having the information in Reference -> Specification -> Buildpack API ? Should it be duplicated / expanded upon in the buildpack author's guide, or some other place? By comparison the Platform API page in the docs is quite bare: https://buildpacks.io/docs/reference/spec/platform-api/

Under "operator's guide":
* analyzed.toml
* group.toml
* metadata.toml
* order.toml
* plan.toml
* project-metadata.toml
* report.toml
* stack.toml

**Comment by natalieparellano** [comment]
Operator issues: https://github.com/buildpacks/docs/issues/251, https://github.com/buildpacks/docs/issues/252, https://github.com/buildpacks/docs/issues/253

**Comment by danielleadams** [comment]
Buildpack Author Issues:
- launch.toml https://github.com/buildpacks/docs/issues/254
- build.toml https://github.com/buildpacks/docs/issues/255
- buildpack plan https://github.com/buildpacks/docs/issues/137

**Comment by samj1912** [comment]
cc: @natalieparellano do we still need to discuss this or do all the related issues cover the expected results from this one?

**Comment by natalieparellano** [comment]
@samj1912 I think we are good here!

**Comment by ForestEckhardt** [comment]
Is this issue still being used to track this overall track of work or are there more issues that need to be opened as a result of this issue?
