### ISSUE TITLE
Document Buildpackages as a core concept

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/docs#158]
## Summary
Now that buildpackages are pretty core to the `pack` CLI, it would be great to document buildpackages as a core concept on the /docs/concepts page. 

I know that buildpacks are documented, but IMO it would be nice to have one place where I can understand the difference between Builders, Buildpacks, and Buildpackages and see how they each relate to one another. 

## What questions should this documentation answer?
- What are buildpackages? How are they different from Builder images?

## Who is the target audience for this documentation?

- [X] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

**Comment by jromero** [comment]
@buildpacks/distribution-contributors, could we provide more clarity on this topic [here](https://buildpacks.io/docs/concepts/components/buildpack/#distribution)?
