### ISSUE TITLE
Better explanation around order groups

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#163]
## Summary
A common gotcha from `[[order]]` and `[[order.group]]` is the understanding of how these two levels work.

## What questions should this documentation answer?
- How do I add all buildpacks to a single group?
- How do I create multiple groups?

## Who is the target audience for this documentation?

- [ ] App Developer
- [x] Buildpack Author (for meta-buildpacks)
- [x] Operator (for create-builder)
- [ ] Other:

## Additional Information
From paketo slack [comment](https://paketobuildpacks.slack.com/archives/CULAS8ACD/p1592832697284000):
![image](https://user-images.githubusercontent.com/475559/85302965-7a08fb80-b46f-11ea-974c-e23207ff2509.png)

**Comment by dfreilich** [comment]
This is in a `builder.toml`?

**Comment by jromero** [comment]
@dfreilich correct.

**Comment by natalieparellano** [comment]
Related: https://github.com/buildpacks/docs/issues/147

**Comment by jromero** [comment]
Given that this is targeting the buildpack authors, would it make more sense to assign this to @buildpacks/buildpack-authors-tooling-contributors? 

/cc: @samj1912
