### ISSUE TITLE
Update docs for Buildpack API 0.4

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#183]
## Summary

Update documentation to Buildpacks API 0.4

## Including
- [ ] Tutorials
- [ ] `.toml` schemas

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by samj1912** [comment]
Related #300

**Comment by samj1912** [comment]
I think this can be closed as we have already updated the docs to CNB api 0.6 https://github.com/buildpacks/docs/pull/337 ? @jromero feel free to re-open if there are any straggling doc updates related to this issue.
