### ISSUE TITLE
Add not-so-similar tools to feature comparison list

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#192]
## Summary

As a potential user, I'd like to know how buildpacks differ from say:

* [x] docker (moby)
* [ ] buildah
* [ ] kaniko
* [ ] bazel
* [ ] makisu

## What questions should this documentation answer?
- How are they different from buildpacks?

## Who is the target audience for this documentation?

- [x] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by jromero** [comment]
Alternative implementation: Create a set of blog posts comparing each tool to buildpacks. Additionally, tag the blog posts so we can have a single aggregated list of posts. (ie: https://medium.com/buildpacks/tagged/docker)

**Comment by samj1912** [comment]
@Harshita-Kanal is currently working on feature comparison related issues as part of the LFX mentorship program.
