### ISSUE TITLE
Add some documentation for contributing to this repository

### ISSUE THREAD

**Issue by quorauk** [buildpacks/docs#20]
It might be useful to have some docs for contributing to the documentation.

Perhaps something like the following in README.md

## Development
This documentation is build using hugo, install it using the guide [here](https://gohugo.io/getting-started/installing/)
```
git clone https://github.com/buildpack/docs.git
cd src
hugo server
# documentation is available at localhost:1313
```

**Comment by Zanadar** [comment]
Should be covered by https://github.com/buildpacks/docs#development
Feel free to re-open @quorauk if you disagree
