### ISSUE TITLE
Using an http proxy during build

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#200]
## Summary

As an app developer in a restricted environment, I need to provide HTTP(s) proxy settings.

## What questions should this documentation answer?
- How do I provide HTTP proxy settings to `pack`?
- Does configuration from `~/.docker/config.json` apply to `pack build`?

## Who is the target audience for this documentation?

- [x] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information

Relevant docker documentation: https://docs.docker.com/network/proxy/#configure-the-docker-client

**Comment by AidanDelaney** [comment]
@jromero I'm happy to take this.
