### ISSUE TITLE
Document buildpacks registries

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#218]
## Summary

Given that we are now releasing a number of experimental commands for buildpack registries (https://github.com/buildpacks/pack/pull/847/, https://github.com/buildpacks/pack/pull/839), we should document the concept.  

The RFCs that are relevant are:
* https://github.com/buildpacks/rfcs/blob/main/text/0022-client-side-buildpack-registry.md
* https://github.com/buildpacks/rfcs/blob/main/text/0032-update-json-cnb-registry.md

## What questions should this documentation answer?
* What is a buildpacks registry?
* Why would I use one? 
* How do I add things to a registry? 
* How do I pull images from a buildpacks registry?

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [x] Operator

**Comment by jromero** [comment]
@buildpacks/distribution-maintainers  / @buildpacks/distribution-contributors This issue has been open for a while. Is there someone that can take this on?

**Comment by jkutner** [comment]
Is this covered by the following?
* https://buildpacks.io/docs/buildpack-author-guide/publish-a-buildpack/
* https://buildpacks.io/docs/buildpack-author-guide/publishing-with-github-actions/

**Comment by jromero** [comment]
I'm content with what we have. If any additional requests come in we can create a new issue.
