### ISSUE TITLE
Document the Bill of Materials (BOM)

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#220]
## Summary
We don't really document the BOM anywhere. It's referenced in the [spec](https://github.com/buildpacks/spec/blob/bea3a7af28500f4f61d95f65f5bd9331b41599af/platform.md#labels) but it's kind of opaque.

## What questions should this documentation answer?
- As an app developer, how do I access the BOM?
- What does the BOM tell me about how the app was built?
- As a buildpack author, how do I ensure that I contribute to the BOM?

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information
This should probably be blocked on https://github.com/buildpacks/lifecycle/issues/396 because the BOM is changing.

**Comment by samj1912** [comment]
Fixed in https://github.com/buildpacks/docs/pull/300

**Comment by samj1912** [comment]
Closing as it is fixed per above :)
