### ISSUE TITLE
Docs should contain a "troubleshooting" section

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#221]
## Summary

It would be nice to have a section that addresses some common errors and provides general guidance for when things go wrong.

## What questions should this documentation answer?

The lifecycle now has more meaningful error codes, we could cover these at a high level (e.g., 10X codes mean detect failure, etc.)

We could cover common gotchas such as not building from inside the app directory.

It might be useful for pack to have its own section, and link to more general documentation where relevant.

From [Slack](https://buildpacks.slack.com/archives/CST4A3ECV/p1601409229015000), one way we could organize things:
```
App Developer’s Guide
…
Operator’s Guide
Troubleshooting
|___ Error Codes
|___ Mounts
|___ …
\___ Networking
```

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by dfreilich** [comment]
There was further discussion on the topic [here](https://buildpacks.slack.com/archives/CST4A3ECV/p1601409073012200). Given that each reference tool may have its own issues and solutions, the suggestion (from @jromero) was to have it be differentiated, together with one top level /troubleshooting section
