### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/docs#225]
## Summary
The [buildpacks.io](https://buildpacks.io) website contains a lot of data. It can be very helpful to have a search box in order to find quickly and easily content in it.

**Comment by dfreilich** [comment]
I was looking for this a few weeks back, and forgot to add an issue. Would love to see this done!

**Comment by dfreilich** [comment]
Hugo has some resources for searching we may want to look into: https://gohugo.io/tools/search/

This also looks really cool, but we'll need a project owner to add it: https://docsearch.algolia.com/

**Comment by jromero** [comment]
I've submitted a request for algolia. 🤞
