### ISSUE TITLE
Mixins documentation is not clear enough

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/docs#228]
## Summary

I think that the Mixins concept could be documented better [here](https://buildpacks.io/docs/concepts/components/stack/#mixins).

## What questions should this documentation answer?
- What are Mixins?
- Why do we need Mixins?
- Are there any other alternative to Mixins?
- How is it possible to check what Mixins are provided by a specific stack?
- How is it possible to check what Mixins are required by a specific buildpack?

In addition to answering the questions above, I think it's worth adding a real example of how Mixins are being used.

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by yaelharel** [comment]
Some ideas on things to add to the documentation:
* Mixins are metadata that stacks provide (it's pre-installed) and buildpacks require.
* Why can't this metadata be provided by buildpacks?
  - It requires root privileges (that buildpacks don't have)
  - It takes a lot of time to install
  - A lot of people apps need these tools (like `grep` or `gzip`)

**Comment by jromero** [comment]
Blocked due to https://github.com/buildpacks/rfcs/pull/172 which may get rid of mixins altogether.
