### ISSUE TITLE
Lifecycle phases should be better documented

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#232]
## Summary

Today we have the following page: https://buildpacks.io/docs/concepts/components/lifecycle/

Each phase has a one sentence description, and `restore` is omitted. The documentation should be more comprehensive, and cover every phase.

## What questions should this documentation answer?

* What is the purpose of the phase?
* How does the phase run, from end-to-end?
* What inputs are relevant for this phase?
* What outputs are relevant for this phase?
* Links to relevant documentation to understand the phase better (e.g., link to page describing `BOM` when describing the build phase)

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by samj1912** [comment]
ping @buildpacks/implementation-contributors
