### ISSUE TITLE
creator and lifecycle image should be documented

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#238]
## Summary
The creator and lifecycle image are mentioned here: https://github.com/buildpacks/docs/blob/5e46a0c4bb46789be8044b0ec479c54728ad9488/content/docs/tools/pack/concepts/trusted_builders.md

However this documentation is very `pack`-specific. We could make the `creator` and lifecycle image documentation more generic so that it would make sense for other platforms (such as Tekton).

We have an issue to document each lifecycle phase: https://github.com/buildpacks/docs/issues/232. Probably it makes sense for the creator documentation to live alongside the documentation of the 5 phases.

## What questions should this documentation answer?
- What does the creator do?
- Why is the creator needed?
- How do I run the creator?
- What is the lifecycle image?
- Why is the lifecycle image needed?
- How do I use the lifecycle image?

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by natalieparellano** [comment]
In my head, it made sense to make a single issue for both creator and the lifecycle image, as they both hinge on the concept of "trust". But maybe there could be separate issues. Or maybe we need another issue to describe the concept of "trust" in a generic way.

**Comment by jromero** [comment]
> In my head, it made sense to make a single issue for both creator and the lifecycle image, as they both hinge on the concept of "trust". But maybe there could be separate issues. Or maybe we need another issue to describe the concept of "trust" in a generic way.

I would vote that they be separate concerns to minimize scope.

FWIW, the create (creator) phase page already exists [here](https://buildpacks.io/docs/concepts/components/lifecycle/create/) but is lacking in information. Also, we have a [blog post](https://medium.com/buildpacks/faster-more-secure-builds-with-pack-0-11-0-4d0c633ca619) for additional information that may be worth linking to.
