### ISSUE TITLE
Caching should be better documented

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#239]
## Summary
We have a request to describe caching the ruby version here: https://github.com/buildpacks/docs/issues/198
And caching is described here: https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/caching/

The existing documentation is pretty brief, and doesn't describe caching at a level that would be useful to platform operators. We should add more comprehensive documentation.

## What questions should this documentation answer?

- How does caching work at a high level? How is the cached scoped - i.e., by app image tag, buildpack id, etc.
- What are the different types of caching that are used (e.g., `cache = true` vs. layer-reuse caching)
- How can caching be configured (e.g., volume cache vs. registry cache)
- How can the cache be cleared?
- What is the "launch cache"?
- How could the cache be used together with arbitrary volume mounts to make things faster?
- What considerations are useful for local vs. remote build environments? (e.g., persistent volume claims in k8s, etc.)
- Other...

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

## Additional Information
This is a broad topic. Perhaps it could be split over several pages or linked to in various places.

**Comment by genevieve** [comment]
This would be wonderful! Hoping this comes out soon 🤞🏻
