### ISSUE TITLE
Guide/tutorial on building a stack

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/docs#249]
## Summary

As an operator, I'd like to have a detailed guide on how to build a stack.

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

## Additional Information

The guide should probably contain some examples and a reference to the mixins documentation (see #228).

**Comment by dfreilich** [comment]
We should also have a dedicated part of this as how to extend another OS stack, to do what you need/allow users to create custom builders.
