### ISSUE TITLE
Platform Author: how to control the location of layers

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#251]
## Summary
Users may want the layers directory to end up somewhere other than `/layers`. To change the location of this directory, for platform API <= 0.4 you need to also specify the location of analyzed.toml, group.toml, and plan.toml via their respective flags. For platform API > 0.5 it is enough to specify `-layers`.

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [x] Platform Author
- [ ] Other:

**Comment by jromero** [comment]
This may be documented here: https://buildpacks.io/docs/platform-guide/
