### ISSUE TITLE
Operator: customizing a builder should be documented

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#253]
## Summary
Today, we document how to specify an order on a builder: https://buildpacks.io/docs/operator-guide/create-a-builder/ but we don't explain how to pass an order to the lifecycle (i.e., `pack` will write the provided `[[order]]` to `/cnb/order.toml` which is the default location, but could also be specified with `-order`). The same is true for `[stack]` and `/cnb/stack.toml`. 

We should document at this level of detail so that operators wishing to customize a builder (or who are not using builders) know how to invoke the lifecycle. We should make clear that this is "advanced". 

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by jromero** [comment]
@samj1912 has volunteered. :)
