### ISSUE TITLE
Document build.toml

### ISSUE THREAD

**Issue by danielleadams** [buildpacks/docs#255]
## Summary
It may be useful to have documentation for the buildpack author of exactly what the `build.toml` is and how it should be used for 1 or multiple buildpacks.

## What questions should this documentation answer?
- What use case do I use a build.toml for? How does it help with dependencies across buildpacks?
- At what point in the build lifecycle should the build.toml be created?
- What is the build.toml expected to contain?

## Who is the target audience for this documentation?

- [ ] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information
Parent Issue: https://github.com/buildpacks/docs/issues/148
Spec: https://github.com/buildpacks/spec/blob/7a3d2865376eb7f1de7fb0728b68a47b62ab9868/buildpack.md#buildtoml-toml

**Comment by samj1912** [comment]
Useful for BP authors to provide build metadata like unmet deps and/or build bom entries. See spec for more details.
