### ISSUE TITLE
Document `buildpack from=builder`

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#258]
## Summary

A question (raised in https://github.com/GoogleCloudPlatform/buildpacks/issues/91), was:
> Is there a way to say to pack to please use a specific buildpack in addition to anything else the builder already knows?

The response (from @jromero) was:
> This is possible via an (apparently) undocumented option --buildpack from=builder. Some example commands:

Buildpack buildpacks/hello-processes is APPENDED to each "order". Hence it uses the buildpacks from the builder.

`pack build my-app --builder cnbs/sample-builder:bionic --buildpack from=builder --buildpack buildpacks/hello-processes`

vs Buildpack buildpacks/hello-processes is PREPENDED to each "order". Hence it uses the buildpacks from the builder.

`pack build my-app --builder cnbs/sample-builder:bionic --buildpack buildpacks/hello-processes --buildpack from=builder`

## What questions should this documentation answer?
- How can we manipulate builders, to pre/append buildpacks onto build orders?

## Who is the target audience for this documentation?

- [x] App Developer
- [ ] Buildpack Author
- [x] Operator

**Comment by samj1912** [comment]
@samj1912 to add a reference to the pre/post buildpack rfc which calls for from=builder to be deprecated.
