### ISSUE TITLE
Provide better specification of the package.toml format

### ISSUE THREAD

**Issue by ryanmoran** [buildpacks/docs#261]
## Summary
The `package.toml` format is currently [documented](https://buildpacks.io/docs/reference/config/package-config/) on [buildpacks.io](https://buildpacks.io). However, this documentation is missing some details.

## What questions should this documentation answer?
- What are the accepted URL formats supported by the `buildpack.uri` or `dependencies.uri` fields? I see some cases that include a `docker://` scheme, and others that do not. What is expected?
- What is the state of the `dependencies.image` key? `pack` will readily create a buildpackage that references the `dependencies.image` key, but it isn't documented anywhere. It has been stated that this field is deprecated and soon to be removed. The documentation should probably state this.

## Who is the target audience for this documentation?

- [ ] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information

Here are a couple examples of different, but still valid `package.toml` files:
1. https://github.com/paketo-buildpacks/ruby/blob/6c306dde424786fe1bce88d8076b7bed97c4aeb9/package.toml
2. https://github.com/paketo-buildpacks/java/blob/01771710c13d5816a31af8b617fa9c40fd703209/package.toml

**Comment by samj1912** [comment]
@jromero to update the issue

**Comment by jromero** [comment]
We have a [reference page](https://buildpacks.io/docs/reference/config/package-config/) and [guide](https://buildpacks.io/docs/buildpack-author-guide/package-a-buildpack/) but are still missing what the possible URI schemes are.
