### ISSUE TITLE
Missing "s" on label used for mixins

### ISSUE THREAD

**Issue by wburningham** [buildpacks/docs#262]
**On Page:** [Stack](https://buildpacks.io/docs/concepts/components/stack/)

The examples for the labels for mixins on a stag image are 

![image](https://user-images.githubusercontent.com/712078/99848011-402f4480-2b36-11eb-9ccc-1daeeebf18cc.png)

But it should be `io.buildpacks.stack.mixins` not `io.buildpack.stack.mixins` (notice the missing "s").

**Comment by jromero** [comment]
![salute](https://media.giphy.com/media/FmBhzktIjvdZe/giphy.gif)
