### ISSUE TITLE
Add option to "Add to Calendar"

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#269]
On the community page, we provide the option to download the `.ics` files for the events so that users can import them into their calendar. Another useful option would be to create a button links to a [Google Calendar link](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/google.md) that would add it to the user's calendar. Additionally, we should continue to provide the ability to download the `.ics` for calendars like Outlook.

### Event Details modal

```
Name: Learning Sub-Team Sync
...
Add to calendar: [Outlook / iCal] [Google Calendar]
```

Considerations: Given that most events are recurring, should the "Save Event" add a series or the single event? The quick solution would be to save the series.

### Calendar Footer Links

Inspired by [GitHub Universe](https://githubuniverse.com/) (see below for screenshots), when a user clicks on a calendar link to a specific calendar on the footer it can bring up a modal with the options:

```
Add these events to your calendar.

**{Name}**

[Outlook / iCal] [Google Calendar]
``` 

## Additional Context

This issue is based on the following feedback:

> * Maybe clarify that the "Add these events to your calendar" is an .ics file, and not "importing into your Google Calendar/other calendar"? Alternatively, if there could be an "import into your calendar", that would also be great
> 
>> Long-term I'd like to do something similar to what GitHub Universe conf did...
>>
>> ![image](https://user-images.githubusercontent.com/475559/101088348-2f8cbe80-3579-11eb-8169-6fe6542cee04.png)
>>
>> ![image](https://user-images.githubusercontent.com/475559/101088371-39aebd00-3579-11eb-8da5-3e4ae2f5877c.png)

_Originally posted by @jromero in https://github.com/buildpacks/docs/issues/267#issuecomment-738310431_

**Comment by asquare14** [comment]
@jromero May I work on this ?

**Comment by jromero** [comment]
All yours. :) 

Let us know if there's any help we can provide.

**Comment by jromero** [comment]
@asquare14, hi again. Are you still interested in working on this issue?
