### ISSUE TITLE
s/id/image for buildpacks list

### ISSUE THREAD

**Issue by wburningham** [buildpacks/docs#281]
**On Page:** [builder.toml](https://buildpacks.io/docs/reference/config/builder-config/)

When specifying a buildpacks in a builder.toml file I think `id` needs to be `image`. It should stay `id` for the order list.

**Comment by jkutner** [comment]
@wburningham The `[[buildpacks]] image` key was deprecated in favor of the `uri` key (which can point to an image using the `docker://` scheme). I think it's possible that `[[buildpacks]] id` could be optional (it must match whats in the buildpackage at `uri` anyways), but I'm not sure if that's allowed in the code.

**Comment by wburningham** [comment]
Got it. Thanks.

**Comment by wburningham** [comment]
I tried testing out the `docker://` scheme, but I can't seem to get it to work.

`builder.toml` before:

```
...
[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/image-labels"
  version = "2.0.6"
...
```


`builder.toml` after:

```
...
[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/image-labels:2.0.6"
...
```

The before works, but the after does not. @jkutner can you spot what I am doing wrong or is there a place I can read up on the migration guide from id -> uri for docker images?

**Comment by jkutner** [comment]
What does `pack --version` show for you?

**Comment by wburningham** [comment]
`0.14.2+git-0fd189d.build-1450`

**Comment by jkutner** [comment]
Ah yea, you'll need [0.15.0](https://github.com/buildpacks/pack/releases/tag/v0.15.0) or newer. If you want to stick with 0.14.x you can use `image`.
