### ISSUE TITLE
Type Error In auth.yaml File

### ISSUE THREAD

**Issue by manshaaazar** [buildpacks/docs#283]
**On Page:** [Tekton](https://buildpacks.io/docs/tools/tekton/)
apiVersion: v1
kind: Secret
metadata:
    name: basic-user-pass
    annotations:
        tekton.dev/docker-0: <LINK TO REGISTRY, e.g. https://index.docker.io/v1>
type: kubernetes.io/basic-auth
stringData:
    username: <USERNAME>
    password: <PASSWORD>
---
Please change the Secret's metadata.name to "basic-user-auth" instead of "basic-user-pass".

**Comment by dfreilich** [comment]
Hey @manshaaazar , thanks for the feedback! We had initially done it like that, to reflect the fact that the auth itself was a `user/password` combination, instead of another kind of secret. Is that unintuitive? I'd just like to understand the motivation behind the desired change.

**Comment by manshaaazar** [comment]
apiVersion: v1
kind: Secret
metadata:
    name: basic-user-auth
    annotations:
        tekton.dev/docker-0: <LINK TO REGISTRY, e.g. https://index.docker.io/v1>
type: kubernetes.io/basic-auth
stringData:
    username: <USERNAME>
    password: <PASSWORD>
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: buildpacks-service-account
secrets:
    - name: basic-user-pass
 

Actually, when we create a SeviceAccount in Kubernetes,  ServiceAccount's Secrets value must match with the Secret.metadata name  we want to use.
But, In the tutorial, the ServiceAccount's Secrets value was not matching with the Secret.metadata name.
