### ISSUE TITLE
Document Stack Buildpacks

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#285]
## Summary

Stack Buildpacks were defined in [RFC 0069](https://github.com/buildpacks/rfcs/blob/main/text/0069-stack-buildpacks.md) (the discussion is in this PR: https://github.com/buildpacks/rfcs/pull/111). 

This is blocked on the successful completion of https://github.com/buildpacks/lifecycle/issues/501 and https://github.com/buildpacks/pack/issues/1021

## What questions should this documentation answer?
- What are Stack Buildpacks?
- What are some potential uses of Stack Buildpacks?
- Why do I need root? 
- Isn't that dangerous?
- How can we ensure ABI compatibility? 
- How do I use them? 
- How do I make them?

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [x] Operator

**Comment by jromero** [comment]
Blocked by ongoing work: https://github.com/buildpacks/lifecycle/issues?q=is%3Aissue+label%3Aepic%2Fstackpacks+
