### ISSUE TITLE
Document launcher

### ISSUE THREAD

**Issue by yaelharel** [buildpacks/docs#287]
## Summary

Add documentation on the `launch` operation [here](https://buildpacks.io/docs/concepts/operations/)

## What questions should this documentation answer?
- What is the `launch` operation?
- How to use it?

## Who is the target audience for this documentation?

- [X] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [ ] Other:

**Comment by natalieparellano** [comment]
Note that we already have some documentation here: https://buildpacks.io/docs/app-developer-guide/run-an-app/#run-a-multi-process-app. But probably it can be improved and made more discoverable.
