### ISSUE TITLE
Add new Buildpack.toml keys

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/docs#288]
**On Page:** [Building blocks of a Cloud Native Buildpack](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb/)

https://github.com/buildpacks/rfcs/pull/127 describes a few new keys for the `buildpack.toml` file; we should add them to the document. 

```
[buildpack]
description = "<buildpack description>"
keywords = [ "<string>" ]
[[buildpack.licenses]]
type = "<string>"
uri = "<uri>"
```

We should also create a reference specification of the `buildpack.toml`, similar to our reference for `package.toml`, `builder.toml`, and `project.toml`.

**Comment by ForestEckhardt** [comment]
So currently there is some `buildpack.toml` schema information [here]( https://buildpacks.io/docs/reference/spec/buildpack-api/#buildpacktoml) in the reference section under the Buildpack API heading. Does it make sense for to add information to have this information be in 3 places? As this issue currently stands there the `buildpack.toml` schema would be in the following places:
- The `Building block of Cloud Native Buildpack` which at the time of writing this appears to be linked to a page on the `Create a Buildpack` tutorial
- The `Buildpacks API` Reference Page
- A new `buildpack.toml` reference article in the Configuration section of the References

It would make more sense to me if these could be condensed in to one location in so reasonable way. What are peoples thoughts on where a schema should live on the website?

**Comment by jromero** [comment]
I like the idea @ForestEckhardt, I would defer to the @buildpacks/buildpack-authors-tooling-maintainers for input on exactly where it should live.
