### ISSUE TITLE
Add Copy/Paste button for all code blocks

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/docs#293]
## Summary

Could y'all look into adding a simple copy/paste button on all code blocks across the website? I feel like this would make it easier to walk through some of the content (especially the getting started tutorials.

**Comment by dfreilich** [comment]
We may have to be selective about how we apply this, given that we occasionally have output of commands in code blocks as well, which we probably wouldn't want to make copyable.

**Comment by asquare14** [comment]
@dfreilich May I work on this ?

**Comment by jromero** [comment]
All yours. :) 

Let us know if there's any help we can provide.

**Comment by jromero** [comment]
@asquare14 👋 , it's been a while. Is this something you are still interested in?
