### ISSUE TITLE
Add a reference slide deck reference

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#326]
## Summary

As a follow up to https://github.com/buildpacks/docs/issues/127 and https://github.com/buildpacks/docs/pull/325, the idea of providing a CNB styled reference slide deck that any community member can use to compile their own presentation.

For reference, the linkerd project provides a slide deck as part of their "meetup-in-a-box": https://linkerd.io/community/meetup-in-a-box/

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [x] Operator
- [x] Other: Anyone presenting CNBs

**Comment by afzal442** [comment]
hi @jromero, let me know how to address this issue? where should this kind of feature be made? thanks

**Comment by ramiyengar** [comment]
Hey folks! I took a stab at this task. Here's a link to my first draft: https://docs.google.com/presentation/d/1geWATRq7vnV8Z12q66GviIqKTCrOmc_RPeHVzShkkDE/edit?usp=sharing

It is open for comments. LMK if anyone needs additional access/ownership. Cheers!
