### ISSUE TITLE
Error: unknown command "buildpack" for "pack"

### ISSUE THREAD

**Issue by fagiani** [buildpacks/docs#328]
**On Page:** [Publish a buildpack](https://buildpacks.io/docs/buildpack-author-guide/publish-a-buildpack/)

Following the guide in the page above, I've tried to run:

```
$ pack buildpack register fagiani/apt
Error: unknown command "buildpack" for "pack"
Run 'pack --help' for usage.
```

I am available to help adjusting the docs if you can point me to the updated way.

Keep Rocking!

**Comment by jromero** [comment]
What version of pack are you currently using? I believe this change occured in version 0.16.0: https://github.com/buildpacks/pack/releases/tag/v0.16.0

The blog post explaining why it was done:
https://medium.com/buildpacks/pruning-pack-cli-commands-434df009667c

**Comment by fagiani** [comment]
Thanks @jromero!

I've just updated my `pack` version and that was it!

I am sorry as it was my mistake.
