### ISSUE TITLE
Add Google Analytics integration to buildpacks.io

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/docs#346]
It would be great if the CNB project could add a Google Analytics integration and some sort of public-facing dashboard around this data to the website. The Paketo Buildpacks project has a site analytics [dashboard](https://datastudio.google.com/u/0/reporting/db924e17-d77d-4b13-8727-df635e775353/page/8KADB) and there's a lot of useful data that we get from this that we could use to inform decisions. 

For CNB, I'm very interested in seeing how a "notable" blog post, mention, or conference talk leads to an uptick in website visits and perhaps pack installs, and getting analytics setup similar to Paketo would be a good start towards trying to measure some of this.

**Comment by jromero** [comment]
I personally love the idea. @jkutner, what do you think?

**Comment by jkutner** [comment]
Sounds great
