### ISSUE TITLE
Add link to community repo on "Community" page

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/docs#357]
## Summary

It would be great if we could link to the [Community repo](https://github.com/buildpacks/community) from the Community page. Some of the content on there (particularly the [contributors guide](https://github.com/buildpacks/community/blob/main/contributors/guide.md)) feels relevant to this page.

## What questions should this documentation answer?
- How do I contribute?
- What's the project roadmap?
- ...

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

**Comment by importhuman** [comment]
I'd like to take this up!

**Comment by jromero** [comment]
Thanks @importhuman. 

We also have this related issue: https://github.com/buildpacks/docs/issues/373. It's a little bit more involved but I'd be happy to discuss it more in length if you're interested. Ignore it if you'd like to just do this simple one. :)

**Comment by importhuman** [comment]
@jromero I'd assumed I'd have to write about that anyway, so please let me know what I should know :)

**Comment by importhuman** [comment]
Cool, I'll try coming up with the initial PR and we can take it from there 😀

**Comment by importhuman** [comment]
Can be closed @buildpacks/learning-maintainers

**Comment by samj1912** [comment]
Yup! Thanks!
