### ISSUE TITLE
Add the kubecon slides

### ISSUE THREAD

**Issue by samj1912** [buildpacks/docs#369]
## Summary

We should add the Kubecon EU 2021 slides to the talks section - https://buildpacks.io/docs/#talks
(We should add the office hours slides as well)
## What questions should this documentation answer?

Links/Description to the slides and the video.

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information

cc: @jromero / @dfreilich  / @jabrown85 / @sclevine 

If you could please add these slides that would be great!

**Comment by jabrown85** [comment]
I see the slides and video on that page now. I'm guessing Stephen took care of it :)

**Comment by jromero** [comment]
FYI, I'm going to add the Office Hour slides to close this of.
