### ISSUE TITLE
Publish a contributor guide

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#373]
## Summary

Take some information from our existing [contributor guide](https://github.com/buildpacks/community/blob/main/contributors/guide.md) and make it more visible via https://buildpacks.io/community/

## What questions should this documentation answer?
- What types of contributions can I make?
- What are the requirements for different type of contributions? (ie. commit signing)
- Where is a good place to start? (ie. good first issues)

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [x] Other: Contributor

**Comment by importhuman** [comment]
@jromero Think we can close this since #379 was merged
