### ISSUE TITLE
Improve description of when builder.toml's order.group.version can be omitted

### ISSUE THREAD

**Issue by edmorley** [buildpacks/docs#384]
**On Page:** [builder.toml](https://buildpacks.io/docs/reference/config/builder-config/)

The description of `order.group.version` currently says:

> version (string, optional, default: inferred)
> The version of the buildpack being referred to. This field may be omitted if the top-level buildpacks list contains only one version of the buildpack.

This led me to try omitting that field, in favour of specifying the version only once in the top-level `buildpacks` list.

However creating the builder failed with:

```
$ pack builder create heroku/buildpacks:20 --config builder-20.toml --pull-policy if-not-present
...
ERROR: processing order: unable to resolve version: multiple versions of heroku/procfile - must specify an explicit version
```

This is because some of the meta-buildpacks in the builder have a transitive dependency on an older version of that buildpack. I wouldn't call these transitive dependencies as being in the "top level buildpacks list", and as such from the currently description it sounds like this should work.

Perhaps a wording like so might be clearer?

> The version of the buildpack being referred to. This field may be omitted if the builder image contains only one version of that buildpack.

**Comment by jromero** [comment]
I agree with the sentiment. More than happy to approve a PR.
