### ISSUE TITLE
Better comparison against alternative tools

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#389]
## Motivation

A frequent question asked about this project is "how does this compare to X?". X is typically Docker but may also be Kaniko, Buildah, and more. The user is looking for a comparison to a) get a better understanding of its capabilities, b) determine which project they should use for their problems.

## Proposed Solution
Design and provide a way to do 1v1 comparisons (see [captiva ](https://www.capterra.com/email-marketing-software/compare/7723-171840/Salesforce-Marketing-Cloud-vs-HubSpot-Marketing)as an example)

## Additional Information

We currently have a "basic" feature comparison [here](https://buildpacks.io/features/) but we need more details for each feature and a better way to display a Buildpacks vs X comparison.

- Discussion in [Learning Sync meeting](https://docs.google.com/document/d/1zBYJsBwcwLZ5huG4nt7t7kYqaL1W_J12WuLsr2a9mAo/edit#heading=h.je9l8fxeujff) between @jromero and @samj1912: 
    - https://www.youtube.com/watch?v=NTQXoaeY3hI&t=1045s

_EDIT: Additional resources_

**Comment by wisdomekpotu** [comment]
Hi @jromero  , My name is Wisdom Ekpotu, I am a Third Year Computer Engineering Student from University of Uyo, Nigeria. I saw this project in the LFX mentorship fall 2021 and I thought this project had some parallels with my skills. I would love to contribute to this project and I'm open to learning any new technologies required for the project.
Also does this project have an official Slack channel that we can join to get more information about the project.I am really looking forward to contributing to this project!

**Comment by ShivamTyagi12345** [comment]
hello @jromero   .Myself Shivam Tyagi . I come here with an interest to work on this Upstream Issue as a part of the LFX mentorship Fall 2021. I have made past contributions to [CNCF / glossary](https://github.com/cncf/glossary/pull/204) and am looking forward to learn further .

**Comment by jromero** [comment]
Hi @wisdomekpotu and @ShivamTyagi12345, nice to meet you both.

@wisdomekpotu, this is our [slack](https://slack.buildpacks.io/). The relevant channels for this issue could be `#general`, `#learning-team`, `#mentoring`.

As an FYI, I just updated the original comment with a video to a discussion that we had about this redesign.

**Comment by ShivamTyagi12345** [comment]
Thanks @jromero 🙂

**Comment by wisdomekpotu** [comment]
Nice Thanks @jromero

**Comment by rgrupesh** [comment]
Hello @jromero 

I went through both above mentioned issue and the video.

If I understood correctly, the task is design and implement in-depth 1v1 comparison of Cloud Native Buildpack with other container build tools(say docker or s2i). I am well versed with the tools and technology required for the project. I have submitted my cover letter along with my resume through LFX portal. I have started my research on various aspects of those build tools. Since, it is open-sourced I would like to be part of the project irrespective of the program. 

I have joined slack, too.

Is there else that I should know of?

**Comment by Asmit2952** [comment]
Hey @jromero. My name is Asmit Malakannawar and I am first year engineering student from Bharati Vidyapeeth, Pune, Maharashtra, India. I went through the issue above and this project matches with my skills and I would like to contribute for the same. This will be my first open-source project to contribute to and to learn new skills. I have started my research on the issue and would like to contribute for the same.

 I have joined slack channel too.

**Comment by wisdomekpotu** [comment]
hi @jromero, the repository link to this repo is not the same as the one on the LFX Mentoring Platform.

this is the link currently on the LFX platform

- Remove fake logger
  https://github.com/buildpacks/pack/pull/389

instead of this one 

- Better comparison against alternative tools
  https://github.com/buildpacks/docs/issues/389

**Comment by wisdomekpotu** [comment]
@jromero , Also I just submitted my CV and cover letter on the LFX Portal to become a mentee on this project.

I have forked this repo began my research on the code base and will start contributing immediately.

**Comment by SanjaySinghRajpoot** [comment]
Hey, @jromero My name is Sanjay Singh Rajpoot and I am a second-year engineering student. I went through this project and find it to be the perfect fit as per my skills. I have applied on the LFX portal. 

Currently, I am going through this Repo to under its working. Would love to contribute even if I don't get selected.

**Comment by jromero** [comment]
@Harshita-Kanal, the first PR #431 was merged to [epic/389-comparison-redesign](https://github.com/buildpacks/docs/tree/epic/389-comparison-redesign).

Here are a few additional changes necessary.

- [ ] Remove old comparison chart
- [ ] Style to buttons to other tools
- [ ] Update links to blog post
