### ISSUE TITLE
Document required/recommended buildpack.toml keys for publishing a buildpack

### ISSUE THREAD

**Issue by edmorley** [buildpacks/docs#408]
**On Page:** [Publish a buildpack](https://buildpacks.io/docs/buildpack-author-guide/publish-a-buildpack/)

The "publishing a buildpack page" (linked above) describes the minimal steps for how to publish a buildpack, however it does not cover adding keys like `[[buildpack.licenses]]` to `buildpack.toml` so that the buildpack's registry listing is fully populated.

Currently this information is mentioned only in the RFC and spec:
https://github.com/buildpacks/rfcs/blob/main/text/0070-new-buildpack-toml-keys.md
https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpacktoml-toml

....which aren't referenced from the docs.

Ideally the docs would either:
1. Mention that there are a number of recommended buildpack metadata fields, and link to the spec entry for more info.
2. Or, explicitly document some of the fields inline in the docs.

**Comment by jromero** [comment]
cc: @buildpacks/distribution-contributors / @buildpacks/distribution-maintainers
