### ISSUE TITLE
Arm support should be documented

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#409]
## Summary
The lifecycle when running on arm64 will produce arm64 images. We should describe this in our docs.

We might also mention (if it's not already covered) that pack can run on Mac M1s but in that case it's using x86 emulation to produce x86 images. 

## What questions should this documentation answer?
- How can I build an arm64 image? (This is a bit tricky because we don't have a "platform" to point people to at the moment. But they could use the creator...)

## Who is the target audience for this documentation?

- [x] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [ ] Other:

**Comment by aemengo** [comment]
@natalieparellano Can I do this one? _**Pick me! Put me in coach!**_
