### ISSUE TITLE
Create a sample app for inline buildpacks

### ISSUE THREAD

**Issue by jkutner** [buildpacks/docs#411]
## Summary

The inline buildpacks documentation shows an example `project.toml`, but it should also link to a working example in https://github.com/buildpacks/samples/tree/main/apps

## What questions should this documentation answer?
- How do I use inline buildpacks?

## Who is the target audience for this documentation?

- [x] App Developer
- [x] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information
https://github.com/buildpacks/docs/pull/365

**Comment by samj1912** [comment]
We still need to resolve this issue by adding this to our katacoda docs
