### ISSUE TITLE
Wrong API version?

### ISSUE THREAD

**Issue by tgquan67** [buildpacks/docs#435]
**On Page:** [Buildpack API](https://buildpacks.io/docs/reference/spec/buildpack-api/#schema)
What is `current` in `api (string, required, current: 0.5)`? If it's latest version, shouldn't it be 0.7?

**Comment by samj1912** [comment]
Thanks for filing this issue :) Yes, it needs to be updated. Would you be open to contributing the changes?

**Comment by tgquan67** [comment]
Sure, I created a PR here https://github.com/buildpacks/docs/pull/436

**Comment by samj1912** [comment]
Fixed in #436
