### ISSUE TITLE
Update outdated BOM content

### ISSUE THREAD

**Issue by scothis** [buildpacks/docs#455]
**On Page:** [Bill of Materials](https://buildpacks.io/docs/features/bill-of-materials/)

This page is documented the previous BOM support that has been deprecated and removed from newly built images. It would be nice to have the current BOM support documented.

**Comment by aemengo** [comment]
Replacement functionality: https://github.com/buildpacks/pack/pull/1351

**Comment by AidanDelaney** [comment]
This was addressed in #465
