### ISSUE TITLE
Buildpack Author's Guide produces error: unknown command "sbom" for "pack"

### ISSUE THREAD

**Issue by ncarlson** [buildpacks/docs#477]
In the Buildpack Author's Guide step 9 of 9, the command `pack sbom download test-ruby-app` produces the following error:

```bash
$ pack sbom download test-ruby-app
Error: unknown command "sbom" for "pack"
Run 'pack --help' for usage.
```

To reproduce:

1. Navigate to step 9 of 9 in the [Buildpack Author's Guide](https://katacoda.com/buildpacks/scenarios/buildpack-author-guide)
2. Execute `pack sbom` in the terminal window
3. Observe the error message `Error: unknown command "sbom" for "pack"`

The `sbom` command appears to have been introduced in [version v0.24.0](https://github.com/buildpacks/pack/releases/tag/v0.24.0) of `pack`, while the katacoda environment provides version 0.23.0+git-0db2c77.build-3056.

```bash
$ pack version
0.23.0+git-0db2c77.build-3056
```

**Comment by AidanDelaney** [comment]
Thanks @ncarlson for the report.  I'm fixing this in https://github.com/buildpacks/docs/pull/479.
