### ISSUE TITLE
Script Install Missing For macOS Intel and macOS Apple Silicon

### ISSUE THREAD

**Issue by conradwt** [buildpacks/docs#485]
### Description

The script install instructions are missing for macOS Intel and macOS Apple Silicon.  When I'm on the GitHub releases page, one is instructed to click the link, https://buildpacks.io/docs/tools/pack.  When I'm on the page for this link, I only see the following:

![Screen Shot 2022-04-02 at 1 55 22 PM](https://user-images.githubusercontent.com/20219/161400938-81cc9979-8a6c-4b1e-a253-a7682d7cfd14.png)

In summary, there are no concrete installation instructions for people that are not using Homebrew for macOS.  For example, one goes from GitHub to the project site and back to GitHub without finding a script command to complete the installation.

### Proposed solution

Add the Script Install tab to display the following when clicked:

```zsh
(curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.24.1/pack-v0.24.1-macos-arm64.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
```

### Describe alternatives you've considered

Alternative this information could very well be added to the release notes on GitHub.

**Comment by jromero** [comment]
This would be a great addition. If anyone would like to take this on, we an almost copy and paste solution. The contents that generate that page are [here](https://github.com/buildpacks/docs/blob/main/data/pack/install.yml).

This is a very similar things we already do for Linux: https://github.com/buildpacks/docs/blob/0d3a1a651cb471afa92033adb41dc2703638da4c/data/pack/install.yml#L52-L58

**Comment by conradwt** [comment]
I'll be happy to get this done for the project.
