### ISSUE TITLE
Remove or migrate katacoda integration

### ISSUE THREAD

**Issue by AidanDelaney** [buildpacks/docs#494]
## Summary

Our documentation relies on katacoda.com for interactive exploration of buildpacks.  [O'Reilly is shutting down katacoda.com](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html). Either remove katacoda integration or migrate to a katacoda alternative.

## What questions should this documentation answer?
- Should we move to a katacoda competitor such as [killercoda](https://killercoda.com/)?
- How can we replace the feel of interactive tutorials without using a katacoda-style system?

## Who is the target audience for this documentation?

- [X] App Developer
- [X] Buildpack Author
- [X] Operator
- [ ] Other:

## Additional Information

Hard deadline of June 15th 2022.

**Comment by samj1912** [comment]
Related https://github.com/kubernetes/website/issues/33936 and https://github.com/thanos-io/thanos/issues/5385

**Comment by AidanDelaney** [comment]
O'Reilly have "set up a separate server for Kubernetes.io".  We're looking at whether we can also get access to this.

**Comment by meeksOreilly** [comment]
Hello, My name is Jesse Meeks, I am a product manager with O'Reilly and I am responsible for Katacoda here. I'm following up on a prior notification concerning the shutdown of Katacoda back on June 15, 2022. I believe my SVP Adam Witwer reached out a few months ago on another issue and mentioned that O'Reilly had set up a dedicated server for Kubernetes.io which would allow the project to continue to use Katacoda. Unfortunately, the dedicated server that was setup for kubernetes.io still relies on an API running on Katacoda.com that is essentially the last remaining service under that domain. While I am mindful of the longstanding partnerships our organizations have enjoyed, I am compelled to share that there are some forces, internal and external, that are increasing the urgency around fully shutting Katacoda.com down. 

I noticed that Katacoda is still referenced in your documentation and assume it's still an important part of that resource. Again, mindful of the history between our orgs, I wanted to reach out to try and get a sense for whether there had been any further discussion on moving away from using Katacoda in your docs? 

Regards,
Jesse

**Comment by AidanDelaney** [comment]
@meeksOreilly Does this mean you have no estimated delivery date for a kubernetes.io katacoda instance?  We have "parked" our katacoda documentation while we await a kubernetes.io instance, would you advise removing these docs instead of waiting for a katacoda instance?

**Comment by AidanDelaney** [comment]
Removed
