### ISSUE TITLE
Please provide SDKMan installation

### ISSUE THREAD

**Issue by zartc** [buildpacks/docs#514]
It would be nice to provide BuildPacks installation via [The Software Development Kit Manager](https://sdkman.io/) (SDKMan).
Having a tool like BuildPacks available via SDKMan will lower the resistance to install it, because _[SDKMan]_ users will know that SDKMan will take complete care of the installation of the tool, at the right place, plus updating env variables automatically whiteout hassle. Just a simple `sdk install buildpacks` and that's all.

Providing a SDKMan archive can be done using the instructions [here](https://sdkman.io/vendors)
Since Buildpacks installation seems to be very simple, it shouldn't take more than a couple of hours to complete.

**On Page:** [Pack](https://buildpacks.io/docs/tools/pack/)

**Comment by AidanDelaney** [comment]
Thanks for this report.  I'll add it to the discussion at our next meeting.  Is this something you'd be interested in creating a PR for?
