### ISSUE TITLE
Add Windows compatibility for building with Podman

### ISSUE THREAD

**Issue by uhryniuk** [buildpacks/docs#515]
### Description

There is currently support listed for building with podman on Linux and MacOS in the documentation [here](https://buildpacks.io/docs/app-developer-guide/building-on-podman/). This is beneficial considering there are more individuals moving towards alternatives to Docker. 

### Proposed solution

Assuming there are no technical limitations with Podman functioning on Windows, it _potentially_ could be adding documentation for assigning the Podman socket (`podman.sock`) to the `DOCKER_HOST` through ssh or another communication method. 

### Additional context
[Building with Podman page](https://buildpacks.io/docs/app-developer-guide/building-on-podman/)

**Comment by AidanDelaney** [comment]
As an update, we've not yet had bandwidth to update the Windows docs.  It's something we will get to eventually.

**Comment by matejvasek** [comment]
Latest versions of `podman` are more friendly. The `podman machine start` will print instruction to what `DOCKER_HOST` shall be set.

On windows it will even try seizing default pipe so setting the envvar may not not required.

For macOS there exist additional package `podman-mac-helper` that will make the socket available at default location `/var/run/docker.sock`.

Only that user has to rembmber is to set machine to the rootful mode `podman machine set --rootful=true` first.
