### ISSUE TITLE
How to download jdk,jre from private repo, how to use my own maven settings.xml

### ISSUE THREAD

**Issue by Sunny-001** [buildpacks/docs#533]
Hi team.
when use `pack cli`， i can download jdk, jre from our private repo, the commands like this:
```
pack build ruoyi-admin:3.2.6 \
    --volume /root/bellsoft-jdk-config:/platform/bindings/bellsoft-jdk-config \
    --volume /root/java-maven-binding:/platform/bindings/my-maven-settings \
    --env BP_MAVEN_BUILT_ARTIFACT=ruoyi-admin/target/*.jar \
    --env BP_JVM_VERSION=8.0.312 \
    --pull-policy if-not-present \
    --path /data/build-package-sample/buildpack-test/RuoYi-Vue \
    --volume /root/maven_repo:/home/cnb/.m2:rw \
    --builder paketobuildpacks/builder:base
```
but in tekton, what should i do.

**Comment by AidanDelaney** [comment]
It looks like the paketo folk document [bindings to provide settings.xml](https://paketo.io/docs/howto/configuration/#what-is-a-binding).  I've only ever used the basic functions in Tekton, but it looks like they have some good docs on configuring mount volumes https://tekton.dev/docs/pipelines/tasks/#mounting-multiple-volumes.  Does this help you?

**Comment by samj1912** [comment]
Closing as this is unrelated to the buildpacks.io project. Please reach out to the paketo team at https://paketo.io for help.
