### ISSUE TITLE
[RFC 0116] Document platform cache cleanup is necessary for newer Platform API versions

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#551]
## Summary
On newer platforms, the lifecycle will no longer delete the old cache image when saving a new cache. This allows the cache image to grow indefinitely.

## What questions should this documentation answer?
- How can I cleanup my cache image?
- What are the benefits of not deleting the old cache? (see RFC)

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [x] Operator
- [ ] Other:

**Comment by dlion** [comment]
We can close this issue since we completed this feature and documented it: https://github.com/buildpacks/rfcs/issues/268
