### ISSUE TITLE
Small typo in the docs section: Using Inline Buildpacks

### ISSUE THREAD

**Issue by hashbou** [buildpacks/docs#566]
**On Page:** [Using Inline Buildpacks](https://buildpacks.io/docs/app-developer-guide/using-inline-buildpacks/)

A little typo in the sentence: 
> You can supplement your app’s build **proces** with custom scripts by creating an inline buildpack.
should be 
> You can supplement your app’s build **process** with custom scripts by creating an inline buildpack.

**Comment by AidanDelaney** [comment]
Thanks for this in https://github.com/buildpacks/docs/pull/567.  Thank you.
