### ISSUE TITLE
Examples that depend on cnbs/sample-builder:bionic are broken

### ISSUE THREAD

**Issue by danistrebel** [buildpacks/docs#579]
## Summary

1. Docs examples refer to the image tag `bionic` for the `cnbs/sample-builder` image. 
2. This breaks the examples since the buildpacks in the samples repo specify a stack as either `alpine` or `jammy` (e.g. [here](https://github.com/buildpacks/samples/blob/main/apps/bash-script/bash-script-buildpack/buildpack.toml#L11-L18)).
3. The `jammy` tag isn't yet available in the [docker hub registry](https://hub.docker.com/r/cnbs/sample-builder/tags).

According to [this comment](https://github.com/buildpacks/docs/pull/578#issuecomment-1491435144) https://github.com/buildpacks/samples/pull/148 should fix the pipeline issues and push `:jammy` tagged sample-builder soon.

Once the sample-builder images are available for jammy the docs referring to `bionic` should be changed to `jammy` (or `alpine` see comment below).

## Additional Information

- Short term workaround for some documentation samples might be to use the `alpine` tag instead. I haven't tested if none of the examples depend on features that aren't available in `alpine`

**Comment by AidanDelaney** [comment]
I really appreciate the clarity of this bug report.  I've chosen to update from `:bionic` to `:jammy` as I know the Heroku ruby runtime is built to work on jammy.  I didn't test it on alpine.
