### ISSUE TITLE
Pack-Cli may be not supported for Ubuntu 23.04 Lunar Lobster.

### ISSUE THREAD

**Issue by askaakura** [buildpacks/docs#590]
**On Page:** [Pack](https://buildpacks.io/docs/tools/pack/)
I tried installing `pack-cli` on Ubuntu 23.04 Lunar Lobster, following the instruction on the page.

While running `apt update` I got:
```
Err:24 https://ppa.launchpadcontent.net/cncf-buildpacks/pack-cli/ubuntu lunar Release                                                  
  404  Not Found [IP: 185.125.190.52 443]
```
and,
```
Error: The repository 'https://ppa.launchpadcontent.net/cncf-buildpacks/pack-cli/ubuntu lunar Release' does not have a Release file.
```
I think it is because Lunar is not supported yet. If it is true, please add a note on the page for clarity.

**Comment by AidanDelaney** [comment]
Thanks for the report.  I've addressed it by allowing our CI system to release to lunar PPA.  That should solve the problem rather than documenting the omission.
