### ISSUE TITLE
Incorrect link of external web page to start a local instance of the Docker v2 registry

### ISSUE THREAD

**Issue by Srishti-j18** [buildpacks/docs#653]
**On Page:** [Cache Images](https://buildpacks.io/docs/app-developer-guide/using-cache-image/)

Hi!
There is a need to correct the link to the external webpage that provides instructions for starting a local instance of the Docker v2 registry. This correction is suggested in the "App Developer Guide" within the "Cache Image" section.

One might encounter the following error if they fail to start the registry container...

![image](https://github.com/buildpacks/docs/assets/96656007/33684968-dfad-4b21-ade3-c5d581cbf8a5)

**Comment by Srishti-j18** [comment]
I am working on fixing this issue.

**Comment by AidanDelaney** [comment]
Rebasing these changes on the latest big update

**Comment by AidanDelaney** [comment]
Thank you for this fix
