### ISSUE TITLE
Refactor Docs: Implement RFC

### ISSUE THREAD

**Issue by AidanDelaney** [buildpacks/docs#656]
## Summary
Implement the Docs refactoring RFC

## What questions should this documentation answer?
- 

## Who is the target audience for this documentation?

- [ ] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [ ] Other:

**Comment by natalieparellano** [comment]
I'd like to work on this :)

**Comment by AidanDelaney** [comment]
Done!
