### ISSUE TITLE
Operator Guide: Dockerfile styling is broken

### ISSUE THREAD

**Issue by ryanbrainard** [buildpacks/docs#660]
**On Page:** [Operator Guide](https://buildpacks.io/docs/operator-guide/)

The styling of the Dockerfiles is broken and showing up like this:

<img width="1280" alt="2024-02-22_09-35-46" src="https://github.com/buildpacks/docs/assets/966764/90bf33da-0975-44df-a0ff-9b2870481510">

Using Chrome Version 122.0.6261.57 (Official Build) (x86_64) on MacOS

**Comment by AidanDelaney** [comment]
Thanks for the report. Fixed in #658.
