### ISSUE TITLE
Document build plan

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#67]
We need to better explain and document the format of build plan. Particularly, the `provides` and `requires` concepts.

References: https://github.com/buildpack/spec/blob/master/buildpack.md#build-plan-toml

This should entail:
* Explaining it as part of the [tutorial](https://buildpacks.io/docs/create-buildpack/make-buildpack-configurable/)
* Adding it to the [buildpack API reference](https://buildpacks.io/docs/reference/buildpack-api/)

**Comment by dfreilich** [comment]
Updated tutorial link: https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable/
