### ISSUE TITLE
package.json is not in JSON format on Tutorial setting up environment

### ISSUE THREAD

**Issue by takuya-o** [buildpacks/docs#675]
**On Page:** [Setting up your local environment](https://buildpacks.io/docs/for-buildpack-authors/tutorials/basic-buildpack/01_setup-local-environment/)

I was following the Buildpack.io tutorial to create a sample application. I found that the package.json file is not in JSON format.

The content of the package.json file is as follows:
```
{
  name = "example-application"
}
```
This file should be written in JSON format. Specifically, the following points are problematic:

: is required after the property name.
Values need to be enclosed in double quotes.
The corrected package.json file is as follows:

JSON
``` JSON
{
  "name": "example-application"
}
```

Could you please update the tutorial documentation to fix this issue?

**Comment by AidanDelaney** [comment]
Thank you for this report.  Sorry it's taken me so long to fix this!
