### ISSUE TITLE
Update `pack-cli` install instructions for arch linux

### ISSUE THREAD

**Issue by anjannath** [buildpacks/docs#726]
## Summary

With availability of the official `pack-cli` package from the arch linux extra repo, arch users can install it by using `sudo pacman -s pack-cli`, currently the documentation instructs users to use the package from AUR

## What questions should this documentation answer?
- 

## Who is the target audience for this documentation?

- [x] App Developer
- [ ] Buildpack Author
- [ ] Operator
- [ ] Other:

## Additional Information

for more information see, https://github.com/buildpacks/pack/pull/2188 and https://github.com/buildpacks/pack/pull/2181

**Comment by AidanDelaney** [comment]
Merged PR.  Thank you
