### ISSUE TITLE
The process to cross compile to arm64 does not works

### ISSUE THREAD

**Issue by fagianijunior** [buildpacks/docs#736]
**On Page:** [Build for ARM architecture](https://buildpacks.io/docs/for-app-developers/how-to/special-cases/build-for-arm/)

I am running it on a x86_64 arch, trying to build a arm64 image, if I run this command inside a OrangePi, it's run fine.

$ pack build java-maven-sample --path samples/apps/java-maven/ --builder heroku/builder:24 --platform linux/arm64
# Generate this error

24: Pulling from heroku/builder
Digest: sha256:f3f5d4e6620e93582c3822acd6c7bc114c5c57d1cf07da2b9b63863ec11f601c
Status: Image is up to date for heroku/builder:24
24: Pulling from heroku/heroku
Digest: sha256:f8a5a5f5e6c8d920d2498a347e48bdfed14622c466a5836fd863c044ba7fe7bc
Status: Image is up to date for heroku/heroku:24
exec /cnb/lifecycle/creator: exec format error
ERROR: failed to build: executing lifecycle: failed with status code: 1

**Comment by AidanDelaney** [comment]
Thanks for this.  Right now buildpacks will build an image that is the same as the architecture you're running on.  We don't yet support building `arm64` on an `amd64` machine (or vice-versa).  Leaving this open so that we add an explanatory note to that documentation page.

**Comment by AidanDelaney** [comment]
We've now merged the explanatory note.
