### ISSUE TITLE
Windows ZIP file is not downloading the pack.exe  file 

### ISSUE THREAD

**Issue by gireeshdhanekula** [buildpacks/docs#78]
https://github.com/buildpack/pack/releases/download/v0.5.0/pack-v0.5.0-windows.zip

**On Page:** [Installing `pack`](https://buildpacks.io/docs/install-pack/)

**Comment by ekcasey** [comment]
@gireeshdhanekula I'm not sure what you mean. I just downloaded the zip file from the link in the docs and was able to extract and run `pack.exe`.

**Comment by dfreilich** [comment]
@gireeshdhanekula I'm assuming that this issue is solved, given that @ekcasey was able to download it appropriately. If it's still an issue, reopen it and we'll try to figure it out.
