### ISSUE TITLE
Add adopters to home page

### ISSUE THREAD

**Issue by jromero** [buildpacks/docs#81]
Based on conversations in the working group meeting, we've agreed to add a showcase of consumers of Cloud Native Buildpacks to our home page.

- [x] Compile list of consumers - [See adopters](https://github.com/buildpacks/community/blob/main/ADOPTERS.md)
- [ ] Propose design - "what is it going to look like?"

**Comment by jromero** [comment]
@Zanadar This is the issue regarding some design work for the docs home screen. The hope would be to give it a slight refresh since we'll be adding a major component.

**Comment by dfreilich** [comment]
@jromero Should this be adopters (as in [here](https://github.com/buildpacks/community/blob/master/ADOPTERS.md)), or consumers?

**Comment by jromero** [comment]
This may be a good candidate for front-end or design specific OSS programs/projects. (ie. [Outreachy](https://github.com/cncf/mentoring/tree/master/outreachy))

**Comment by AidanDelaney** [comment]
I wonder if we should move this list to a section on our front page?

**Comment by jromero** [comment]
From a design perspective, I was hoping we can get something visually similar to:
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/475559/187231064-0e8515b0-3a9f-4fab-a142-c78c35b71a09.png">

Source: https://linkerd.io/
