### ISSUE TITLE
Update Buildpack Author's Guide to API v3

### ISSUE THREAD

**Issue by alexbrand** [buildpacks/docs#82]
The ["Building blocks of a Cloud Native Buildpack"](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb/) section of the Buildpack Author's Guide uses the v2 Buildpack API.

Update the guide to use the v3 API.

**Comment by jromero** [comment]
This is an unfortunate naming conflict. The overall project "Cloud Native Buildpacks" is also described as "Buildpacks API v3" as per the spec.

The "Buildpack API" version depicted in the tutorial is a lower level version of the interface between the lifecycle and the buildpacks as described in rfcs [10](https://github.com/buildpack/rfcs/blob/master/text/0010-api-versions.md) and [11](https://github.com/buildpack/rfcs/blob/master/text/0011-lifecycle-descriptor.md#what-it-is). All within the Buildpack API v3 spec.

```text
                  P                          B
                  l                          u
                  a                          i
+----------+      t      +------------+      l      +-----------+
|          |      f      |            |      p      |           |
| Platform | <--- o ---> |  Lifecycle | <--- a ---> | Buildpack |
|          |      r      |            |      c      |           |
+----------+      m      +------------+      k      +-----------+

                  A                          A
                  P                          P
                  I                          I

```

We can see the confusion, we'll discuss this in our next working group meeting.

**Comment by jkutner** [comment]
Does #64 resolve this?

**Comment by jromero** [comment]
Assuming you are referring to https://github.com/buildpack/spec/pull/64. It _partly_ does. I have a few other action items that came out of this. I can assign this to myself and close it once those items are complete.

- [x] Update spec title
- [ ] Update spec repo description
- [ ] Add additional documentation around buildpack.toml regarding API
- [ ] Rename Buildpack API v3 mentions on the website home page
- [ ] Create an RFC to remove `v3` nomenclature
