### ISSUE TITLE
Next stop, the end

### ISSUE THREAD

**Issue by phluks** [buildpacks/docs#96]
**On Page:** [An App&#39;s Brief Journey from Source to Image](https://buildpacks.io/docs/app-journey/)

The referenced build docker image cnbs/sample-builder does not exist on hub.docker.com

**Comment by jromero** [comment]
The image is here: https://hub.docker.com/r/cnbs/sample-builder/tags

What error are you getting?

**Comment by phluks** [comment]
Hi @jromero 

Thank you for responding.

I see. Pulling the image with docker works, but I get this error with pack:
```
pack build myapp --builder cnbs/sample-builder:bionic
ERROR: failed to fetch builder image 'index.docker.io/cnbs/sample-builder:bionic': connect to repo store 'index.docker.io/cnbs/sample-builder:bionic': <empty transport.Error response>
```
This also happens to me if the image exists locally:
```
docker images --format "{{.Repository}}:{{.Tag}} - {{.CreatedAt}}" cnbs/sample-builder:bionic
cnbs/sample-builder:bionic - 2019-10-10 20:40:22 +0200 CEST
```

I'm running the Linux version of pack on Ubuntu 18.04
```
pack version
v0.5.0 (git sha: c9cfac75b49609524e1ea33f809c12071406547c)

docker version
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4
 Git commit:        1752eb3
 Built:             Sat Nov 16 01:05:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
I hope this is helpful.

Best regards, Olav

**Comment by jromero** [comment]
This seems to be a communication issue with dockerhub. We could try a few things via [slack](https://slack.buildpacks.io/) to troubleshoot it.

Things that should be looked at are:

1. Network access to domain `index.docker.io`
2. Any credentials or credhelpers that might be misconfigured in `~/.docker/config.json`

**Comment by phluks** [comment]
1. Network looks ok
```
curl -v index.docker.io/cnbs/sample-builder:bionic
*   Trying 34.199.228.78...
* Connected to index.docker.io (34.199.228.78) port 80 (#0)
> GET /cnbs/sample-builder:bionic HTTP/1.1
> Host: index.docker.io
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< content-length: 0
< location: https://index.docker.io/cnbs/sample-builder:bionic
< 
* Connection #0 to host index.docker.io left intact
```

2. docker login and docker push works

**Comment by phluks** [comment]
I've ping'ed you on slack :-)

**Comment by phluks** [comment]
Upgraded and "un-snap'ed" docker. Now it works.
